-- Seed data, applied on a fresh database by `pnpm dev` (--include-seed on the first push).
--
-- The owner's e-mail is not seeded here on purpose: it is installation-specific and lives
-- in OWNER_EMAIL. `pnpm dev` runs `pnpm db:owner` right after, which allowlists it and
-- creates the user.
--
-- Default categories are not here either: they are seeded per household by the
-- `seed_default_categories` trigger, which is the only place that knows the household id.
