#!/usr/bin/env node
/**
 * Writes deploy/.env with freshly generated secrets. Called by scripts/stack.mjs on the
 * first run; you rarely invoke it by hand.
 *
 * This exists because the Supabase CLI's local stack ships a JWT secret and `anon` /
 * `service_role` keys that are **fixed and public** — the same in every installation.
 * Reused on anything reachable from outside the machine they would let anyone forge a
 * `service_role` token, and the whole RLS model (SPEC §5.4) would be decoration. Nothing in
 * the stack has a default: docker compose refuses to start with any of these missing.
 *
 * The two keys are HS256 JWTs signed with the generated secret, exactly like Supabase's:
 * GoTrue signs sessions with it and PostgREST verifies them with it, so the three must
 * always come from the same run of this script.
 *
 *   node scripts/gen-secrets.mjs [path]     # default: deploy/.env
 */

import { createHmac, randomBytes } from 'node:crypto';
import { existsSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

// Default anchored to the repository, not to the shell's cwd: this is run from deploy/ as
// often as from the root, and it must mean the same file either way.
const repoRoot = fileURLToPath(new URL('..', import.meta.url));
const target = process.argv[2]
  ? resolve(process.cwd(), process.argv[2])
  : resolve(repoRoot, 'deploy/.env');

if (existsSync(target)) {
  console.error(
    `${target} already exists — refusing to overwrite it.\n` +
      'Regenerating the secrets invalidates every session and locks the app out of its own\n' +
      'database. Move the file aside first if that is really what you want.',
  );
  process.exit(1);
}

const base64url = (input) => Buffer.from(input).toString('base64url');

/** Supabase-shaped API key: an HS256 JWT whose `role` claim is the Postgres role. */
function signKey(role, secret) {
  const issuedAt = Math.floor(Date.now() / 1000);
  const header = base64url(JSON.stringify({ alg: 'HS256', typ: 'JWT' }));
  const payload = base64url(
    JSON.stringify({
      role,
      iss: 'supabase',
      iat: issuedAt,
      // Ten years: these are installation keys, rotated by regenerating the whole file.
      exp: issuedAt + 10 * 365 * 24 * 60 * 60,
    }),
  );
  const signature = createHmac('sha256', secret).update(`${header}.${payload}`).digest('base64url');
  return `${header}.${payload}.${signature}`;
}

const jwtSecret = randomBytes(32).toString('base64url'); // > 32 chars, as GoTrue requires
const postgresPassword = randomBytes(24).toString('base64url');

const contents = `# Generated by scripts/gen-secrets.mjs on ${new Date().toISOString()}.
# The only env file in this repository: docker compose reads it, and \`pnpm dev\` passes the
# three SUPABASE_* values to the Next server it starts. Secrets — never commit it. Keep a
# copy somewhere safe: regenerating JWT_SECRET invalidates every session, and losing
# POSTGRES_PASSWORD locks you out of the database.
#
# Secrets and ports, nothing else. Who owns this installation is a fact of the database,
# not of a config file: \`pnpm db:owner <email>\` writes it once, and everything after that
# reads it from there.

# Where the API answers *from the host* — the loopback port Caddy publishes. Inside the
# compose network the same API is http://caddy:8000, which is what the web container uses.
SUPABASE_URL=http://127.0.0.1:8000

# --- generated: do not edit by hand ---
# Password of every Postgres role (postgres, authenticator, supabase_auth_admin).
POSTGRES_PASSWORD=${postgresPassword}
# Signs the session JWTs. The two keys below are derived from it: change it and they must
# be regenerated together, or the only symptom is a bare 401.
JWT_SECRET=${jwtSecret}
SUPABASE_ANON_KEY=${signKey('anon', jwtSecret)}
SUPABASE_SERVICE_ROLE_KEY=${signKey('service_role', jwtSecret)}
`;

writeFileSync(target, contents, { mode: 0o600 });
console.log(`wrote ${target} (mode 600)`);
